# Site
name: "Notes from the life of a programmer"
title: "Notes from the life of a programmer"
description: "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: 'https://dominikjeske.github.io'
baseurl: ''
google_analytics: 'G-S31209TFHT'
disqus: 'notes-from-the-life-of-a-programmer'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dnf:
    name: Dominik Jeske
    display_name: dnf
    gravatar: 2927a2e304e3714b26552d37f960323c
    email: dominik.jeske@hotmail.com
    web: https://dominikjeske.github.io/
    twitter: https://twitter.com/jeskdom
    description: "My description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
